### ISSUE TITLE
[Bug] Some Languages Showing empty squares in app

### ISSUE THREAD

**Issue by DraconicNEO** [dezem/AtmoXL-Titel-Installer#17] opened 2022-01-22 20:37 UTC
When I enter the language selection Menu in the app it seems that some of the languages are bugged and show empty boxes instead of the language symbols. When switching to those languages the missing symbols changes though.

For Example on the English setting the Korean Characters are Missing
![2022012305001600-FABBE04B5BB8324A427618E6D5E2ED75](https://user-images.githubusercontent.com/44508470/150653941-28457aa0-2bb5-4def-899b-fc5e1fdd8e6a.jpg)

On the Korean Setting Some Chinese characters are missing
![2022012305024200-FABBE04B5BB8324A427618E6D5E2ED75](https://user-images.githubusercontent.com/44508470/150653997-d98fa0a0-d4f3-43ab-bd2c-d58d4d868cf7.jpg)

and on the Chinese setting Korean is missing as well as the special characters from french and spanish. It also Breaks other things such as the spacing of Russian Characters.
![2022012305030600-FABBE04B5BB8324A427618E6D5E2ED75](https://user-images.githubusercontent.com/44508470/150654441-e15659d9-262e-44c1-abea-3ac033377938.jpg)

These issues aren't limited to just the language selection Menu unfortunately. If you have NSP/XCI/NSZ/XCZ files or folders in any of these languages it will mess up their text as well. Here's an example of that:
![2022012305293900-FABBE04B5BB8324A427618E6D5E2ED75](https://user-images.githubusercontent.com/44508470/150654588-50f426c6-8d3e-4581-8a8c-1f654d86045c.jpg)

**Comment by dezem** [comment] 2022-01-22 22:20
Hi there,
yes i know the problem, you must stay at one language and don't mix it up with different langs.

The problem is, that i must load the special char set for languages like chinese. Because the chars are missing on the default set. Then you get the squares if its missing. It depends on the language! 

Look here 
https://github.com/dezem/AtmoXL-Titel-Installer/blob/dc8b926943d8d5bad40ea2cc2589559a4ff0a4a8/source/util/lang.cpp#L46

**Comment by DraconicNEO** [comment] 2022-01-25 02:39
> Hi there, yes i know the problem, you must stay at one language and don't mix it up with different langs.
> 
> The problem is, that i must load the special char set for languages like chinese. Because the chars are missing on the default set. Then you get the squares if its missing. It depends on the language!
> 
> Look here
> 
> https://github.com/dezem/AtmoXL-Titel-Installer/blob/dc8b926943d8d5bad40ea2cc2589559a4ff0a4a8/source/util/lang.cpp#L46

I see, how come this isn't an issue on other installers/file managers, they're able display it just fine?

**Comment by dezem** [comment] 2022-01-25 18:45
All installers which use Plutonium, like Awoo/Tinleaf... should have the same problem.

https://github.com/dezem/Plutonium/blob/53bc5c3eb633069b1a61364fd8cea502682f7fad/Plutonium/Include/pu/ui/render/render_SDL2.hpp#L32-L40

I have currently no solution for it.

**Comment by DraconicNEO** [comment] 2022-01-25 21:07
> All installers which use Plutonium, like Awoo/Tinleaf... should have the same problem.
> 
> https://github.com/dezem/Plutonium/blob/53bc5c3eb633069b1a61364fd8cea502682f7fad/Plutonium/Include/pu/ui/render/render_SDL2.hpp#L32-L40
> 
> I have currently no solution for it.

What about Goldleaf, doesn't that also use plutonium?

**Comment by R-YaTian** [comment] 2022-01-27 00:37
> > All installers which use Plutonium, like Awoo/Tinleaf... should have the same problem.
> > https://github.com/dezem/Plutonium/blob/53bc5c3eb633069b1a61364fd8cea502682f7fad/Plutonium/Include/pu/ui/render/render_SDL2.hpp#L32-L40
> > I have currently no solution for it.
> 
> What about Goldleaf, doesn't that also use plutonium?

Goldleaf use a newer version of Plutonium with different ttf font render. I will try to implement this with a new PR when I have free time. But I can't promise anything.

**Comment by dezem** [comment] 2022-01-29 18:20
Closed, fixed with -> https://github.com/dezem/AtmoXL-Titel-Installer/releases/tag/1.7.0
Thanks @R-YaTian 👍

**Closed by dezem** 2022-01-29 18:20 UTC
